site_name: CompanyGram

#site_url: https://github.com/oa-formation/mkdocs-publish
repo_url: https://github.com/oa-formation/mkdocs-publish
repo_name: mkdocs_companygram

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
nav:
  - Home: index.md
  - About: about.md
  - Images:
    - Posting Images: images/posting.md
    - Liking Images: images/liking.md
    - Sharing Images: images/sharing.md


